# Generated by Django 2.0.2 on 2018-03-26 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=20)),
                ('shcoolID', models.IntegerField()),
                ('emial', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
