# Generated by Django 2.0.2 on 2018-03-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
