# Generated by Django 2.0.2 on 2018-03-27 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0002_auto_20180326_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_file',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=40)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioWeb.User')),
            ],
        ),
    ]
