# Generated by Django 2.0.3 on 2018-05-16 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0003_update_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update_file',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='update_file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='update_file',
            name='path',
        ),
        migrations.AddField(
            model_name='update_file',
            name='CDS',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 6, 23, 2, 316867, tzinfo=utc), max_length=100),
        ),
        migrations.AddField(
            model_name='update_file',
            name='DEFINITION',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 6, 23, 2, 316867, tzinfo=utc), max_length=500),
        ),
        migrations.AddField(
            model_name='update_file',
            name='LOCUS',
            field=models.CharField(default=datetime.datetime(2018, 5, 16, 6, 23, 2, 316867, tzinfo=utc), max_length=50),
        ),
        migrations.AddField(
            model_name='update_file',
            name='ORIGIN',
            field=models.TextField(default=datetime.datetime(2018, 5, 16, 6, 23, 2, 317867, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='update_file',
            name='translation',
            field=models.TextField(default=datetime.datetime(2018, 5, 16, 6, 23, 2, 317867, tzinfo=utc)),
        ),
    ]
