# Generated by Django 2.0.3 on 2018-05-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0005_auto_20180516_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_images',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('Aimg', models.ImageField(upload_to='img')),
                ('Timg', models.ImageField(upload_to='img')),
                ('Cimg', models.ImageField(upload_to='img')),
                ('Gimg', models.ImageField(upload_to='img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioWeb.User')),
            ],
        ),
    ]
