# Generated by Django 2.0.3 on 2018-05-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0006_update_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_images',
            name='Aimg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='update_images',
            name='Cimg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='update_images',
            name='Gimg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='update_images',
            name='Timg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='update_images',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioWeb.Update_file'),
        ),
    ]
