# Generated by Django 2.0.3 on 2018-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0007_auto_20180516_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_file',
            name='xid',
            field=models.IntegerField(default=0),
        ),
    ]
