# Generated by Django 2.0.3 on 2018-05-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0008_update_file_xid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statist_img',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('tongji_img', models.CharField(default='', max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioWeb.Update_file')),
            ],
        ),
    ]
