# Generated by Django 2.0.3 on 2018-05-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioWeb', '0010_perp_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perp_img',
            old_name='pretine_img',
            new_name='pertine_img',
        ),
    ]
